id: P6E3FC463
initial_creation_type: ocr
source_metadata:
  volumes:
    9f5fcccf56a04f828c2a2ad80aad1429:
      base_file: v067.txt
      image_group_id: I1PD95912
      title: ཀུན་ཏུ་བཟང་པོའི་སྤྱོད་པའི་སྨོན་ལམ་གྱི་རྒྱལ་པོའི་བཤད་པ།
      total_pages: 1529
      volume_number: 67
